FROM node:19-alpine
ENV NODE_ENV=production
WORKDIR /app
COPY ["package.json", "package-lock.json", "./"]
RUN npm install --production
COPY ./server /app/server/
EXPOSE 8080
CMD ["npm", "run", "start"]